name: First Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  example-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome Message
        run: echo "Welcome to our program"
